name: 'prototipo-mapa-PET'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
